# Generated by Django 2.2 on 2019-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190619_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='site',
            field=models.CharField(default='https://', max_length=100),
        ),
    ]
