# Generated by Django 2.2 on 2019-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190619_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='challenger',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='job',
            name='team',
            field=models.CharField(default='', max_length=200),
        ),
    ]
