# Generated by Django 2.2 on 2019-08-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190813_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='challenger',
            new_name='challenge',
        ),
    ]
