# Generated by Django 2.2 on 2019-08-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190815_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='keywords',
        ),
    ]
