# Generated by Django 2.2 on 2019-05-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
