# Generated by Django 2.2 on 2019-05-30 10:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190529_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
    ]
